source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.5'
gem 'mysql2', '< 0.5' # still right in rails 6?
# Use SCSS for stylesheets
gem 'autoprefixer-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

gem 'mini_racer', '< 0.5.0', platforms: :ruby

gem 'puma'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '>= 2.0.4', group: :doc

# Security Updates
gem 'devise', '>=4.6.0'
gem 'loofah', '>= 2.2.1'
gem 'rails-html-sanitizer', '>= 1.0.4'
gem 'rack', '>= 1.6.11'
gem 'nokogiri', '>= 1.8.5'
gem 'rake', '>= 12.3.3'
gem 'json', '>= 2.3.0'
gem 'sprockets', '>= 3.7.2'
gem 'activejob', '>= 4.2.11'
gem 'actionview', '>= 5.2.4.2'
gem 'actionpack', '>= 5.2.4.6'

# Rails 6
gem 'sassc-rails'
gem 'flatpickr_rails'



gem 'activerecord-session_store'

group :development, :test do
	gem 'railroady', '~> 1.4', '>= 1.4.2'

	gem 'spring', '~> 1.3.6', group: :development

	gem 'pry-byebug'
end

