source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '= 4.2.10'
# Use sqlite3 as the database for Active Record
gem 'mysql2', '< 0.5'
# Use SCSS for stylesheets
gem 'autoprefixer-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

gem 'mini_racer'

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'devise'
gem 'flatpickr_rails'

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring


gem 'mail'
gem 'nokogiri'


gem 'activerecord-session_store'

group :development, :test do
	gem 'railroady', '~> 1.4', '>= 1.4.2'

	gem 'spring', '~> 1.3.6', group: :development

	gem 'pry-byebug', '= 3.6.0'
	gem 'pry', '= 0.12'
end

