version: '3'
services:
  app-db:
    image: mysql:5.7
    volumes:
      - "./db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PW}
    networks:
      - backend

  app-pma:
    depends_on:
      - app-db
    image: phpmyadmin/phpmyadmin:5.0.0
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}
      PMA_HOST: app-db
      PMA_ABSOLUTE_URI: ${PMA_URI}
    networks:
      - backend

  app:
    build:
      context: rails-app
      dockerfile: Dockerfile
    depends_on:
      - app-db
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_DB_PREFIX: ${MYSQL_DB_PREFIX}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PW: ${MYSQL_USER_PW}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_PORT: ${RAILS_PORT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
      BASE_URL: ${BASE_URL}
    restart: unless-stopped
    volumes:
      - ./rails-app:/usr/app
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    networks:
      - backend

networks:
  backend:
